CREATE TABLE financial_report_material (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source_key CHAR(64) NOT NULL,
    source_path VARCHAR(1024) NOT NULL,
    file_name VARCHAR(300) NOT NULL,
    sha256 CHAR(64) NOT NULL,
    ocr_sha256 CHAR(64) NOT NULL DEFAULT '',
    stock_code VARCHAR(20) NOT NULL DEFAULT '',
    company VARCHAR(120) NOT NULL,
    report_year INT NULL,
    report_period VARCHAR(8) NOT NULL DEFAULT '',
    report_kind VARCHAR(20) NOT NULL,
    identity_status VARCHAR(20) NOT NULL,
    content_source VARCHAR(20) NOT NULL,
    content_state VARCHAR(20) NOT NULL,
    notes VARCHAR(1000) NOT NULL DEFAULT '',
    pages JSON NOT NULL,
    page_count INT NOT NULL DEFAULT 0,
    text_page_count INT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_financial_material_source (source_key),
    KEY idx_financial_material_identity (stock_code,report_year,report_period),
    KEY idx_financial_material_hash (sha256)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
