// Generated by scripts/generate_v3_contracts.py. Edit the Python contract, then regenerate.
export interface AxisEditV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "comparison_axis";
  value: "years" | "companies" | "none";
}

export interface CalculationEditV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "calculation";
  value: "none" | "difference" | "yoy" | "relative_percent" | "percentage_points";
}

export interface CheckV3 {
  name: string;
  status: "pass" | "fail" | "unknown" | "not_applicable";
  detail: string;
}

export interface ClarificationChoicesV3 {
  field?: "metrics";
  family: string;
  options: Record<string, "operating_revenue" | "total_operating_revenue" | "main_business_revenue" | "net_profit" | "attributable_net_profit" | "deducted_attributable_net_profit" | "operating_cost" | "gross_profit" | "gross_margin" | "net_margin" | "eps_basic" | "eps_diluted" | "roe_weighted" | "roe_weighted_deducted" | "roe_diluted" | "total_assets" | "total_liabilities" | "total_equity" | "cash" | "receivables" | "inventory" | "trading_assets" | "construction" | "payables" | "advances" | "contract_liabilities" | "short_loans" | "retained_earnings" | "operating_profit" | "total_profit" | "other_income" | "selling_expense" | "administration_expense" | "finance_expense" | "research_expense" | "tax_surcharges" | "total_operating_cost" | "asset_impairment" | "credit_impairment" | "operating_cash_flow" | "investing_cash_flow" | "financing_cash_flow" | "net_cash_change" | "sales_cash" | "investment_cash_paid" | "cash_begin" | "cash_end" | "debt_ratio" | "net_assets_per_share" | "operating_cash_per_share" | "operating_revenue_reported_yoy" | "total_operating_revenue_reported_yoy" | "attributable_net_profit_reported_yoy" | "net_profit_reported_yoy" | "deducted_attributable_net_profit_reported_yoy" | "total_assets_reported_yoy" | "total_liabilities_reported_yoy" | "net_cash_change_reported_yoy" | "total_assets_reported_change_vs_year_end" | "total_liabilities_reported_change_vs_year_end">;
}

export interface CollectionEditV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "all_companies";
  value: boolean;
}

export interface CompanyEditV3 {
  operation: "replace" | "add" | "remove" | "keep" | "inherit" | "clear";
  text?: string;
  field: "codes";
  value: Array<string>;
}

export interface CompanyMentionV3 {
  text: string;
  kind: "explicit" | "context" | "collection" | "ambiguous" | "uncovered" | "candidate";
  codes: Array<string>;
}

export interface ComputedReferenceV3 {
  id: string;
  data_version: string;
  inputs: [string, string];
  calculation: "difference" | "yoy" | "relative_percent" | "percentage_points";
  comparison_axis: "years" | "companies";
  metric: string;
  scope: "consolidated" | "parent";
  company: string;
  year: number;
  period: "FY" | "HY" | "Q1" | "Q3";
  value: string | null;
  unit: "元" | "%" | "元/股" | "百分点";
  formula: string;
  label: string;
  detail?: string;
}

export interface ConditionsV3 {
  codes?: Array<string>;
  all_companies?: boolean;
  metrics?: Array<string>;
  scope?: "consolidated" | "parent";
  time?: TimeSelectionV3;
  presentation?: PresentationV3;
  restrictions?: RestrictionsV3;
  calculation?: "none" | "difference" | "yoy" | "relative_percent" | "percentage_points";
  comparison_axis?: "years" | "companies" | "none";
  origins?: Record<string, OriginV3>;
}

export interface ContextReferenceV3 {
  text: string;
  target: "company" | "fact" | "financial_task";
  number?: "singular" | "plural";
}

export interface DialogueStateV3 {
  version?: 3;
  revision?: number;
  topic?: string;
  legacy_scope_unknown?: boolean;
  conditions?: ConditionsV3;
  active_goals?: Array<GoalV3>;
  goal_conditions?: Record<string, ConditionsV3>;
  suspended?: ConditionsV3 | null;
  pending?: RequestV3 | null;
  recent_facts?: Array<FactReferenceV3>;
  recent_computed?: Array<ComputedReferenceV3>;
  interrupted_request?: InterruptedRequestV3 | null;
  last_execution?: ExecutionV3 | null;
  executions?: Array<ExecutionV3>;
  modifications?: Array<CompanyEditV3 | MetricEditV3 | ScopeEditV3 | CollectionEditV3 | CalculationEditV3 | AxisEditV3 | EditTimeModeV3 | EditTimeYearsV3 | EditTimePeriodsV3 | EditTimeSpanV3 | EditTimePairsV3 | EditTimeSingleQuarterV3 | EditTimeQuartersV3 | EditPresentationUnitV3 | EditPresentationDecimalsV3 | EditPresentationFormatV3 | EditPresentationChartTypeV3 | EditPresentationOrderV3 | EditPresentationLimitV3 | EditPresentationIncludeInputsV3 | EditRestrictionsNoQueryV3 | EditRestrictionsNoChartV3 | EditRestrictionsNoRepeatV3 | EditRestrictionsExcludedCodesV3 | EditRestrictionsExcludedMetricsV3 | TimeEditV3 | PresentationEditV3 | RestrictionEditV3>;
}

export interface EditPresentationChartTypeV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "presentation.chart_type";
  value: "line" | "bar" | "pie" | "scatter";
}

export interface EditPresentationDecimalsV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "presentation.decimals";
  value: number | null;
}

export interface EditPresentationFormatV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "presentation.format";
  value: "auto" | "text" | "table" | "chart";
}

export interface EditPresentationIncludeInputsV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "presentation.include_inputs";
  value: boolean;
}

export interface EditPresentationLimitV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "presentation.limit";
  value: number | null;
}

export interface EditPresentationOrderV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "presentation.order";
  value: "asc" | "desc";
}

export interface EditPresentationUnitV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "presentation.unit";
  value: "元" | "万元" | "亿元" | "%" | "元/股" | null;
}

export interface EditRestrictionsExcludedCodesV3 {
  operation: "replace" | "add" | "remove" | "keep" | "inherit" | "clear";
  text?: string;
  field: "restrictions.excluded_codes";
  value: Array<string>;
}

export interface EditRestrictionsExcludedMetricsV3 {
  operation: "replace" | "add" | "remove" | "keep" | "inherit" | "clear";
  text?: string;
  field: "restrictions.excluded_metrics";
  value: Array<"operating_revenue" | "total_operating_revenue" | "main_business_revenue" | "net_profit" | "attributable_net_profit" | "deducted_attributable_net_profit" | "operating_cost" | "gross_profit" | "gross_margin" | "net_margin" | "eps_basic" | "eps_diluted" | "roe_weighted" | "roe_weighted_deducted" | "roe_diluted" | "total_assets" | "total_liabilities" | "total_equity" | "cash" | "receivables" | "inventory" | "trading_assets" | "construction" | "payables" | "advances" | "contract_liabilities" | "short_loans" | "retained_earnings" | "operating_profit" | "total_profit" | "other_income" | "selling_expense" | "administration_expense" | "finance_expense" | "research_expense" | "tax_surcharges" | "total_operating_cost" | "asset_impairment" | "credit_impairment" | "operating_cash_flow" | "investing_cash_flow" | "financing_cash_flow" | "net_cash_change" | "sales_cash" | "investment_cash_paid" | "cash_begin" | "cash_end" | "debt_ratio" | "net_assets_per_share" | "operating_cash_per_share" | "operating_revenue_reported_yoy" | "total_operating_revenue_reported_yoy" | "attributable_net_profit_reported_yoy" | "net_profit_reported_yoy" | "deducted_attributable_net_profit_reported_yoy" | "total_assets_reported_yoy" | "total_liabilities_reported_yoy" | "net_cash_change_reported_yoy" | "total_assets_reported_change_vs_year_end" | "total_liabilities_reported_change_vs_year_end">;
}

export interface EditRestrictionsNoChartV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "restrictions.no_chart";
  value: boolean;
}

export interface EditRestrictionsNoQueryV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "restrictions.no_query";
  value: boolean;
}

export interface EditRestrictionsNoRepeatV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "restrictions.no_repeat";
  value: boolean;
}

export interface EditTimeModeV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "time.mode";
  value: "explicit" | "calendar_years" | "latest_common" | "latest_each" | "latest";
}

export interface EditTimePairsV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "time.pairs";
  value: Array<[number, "FY" | "HY" | "Q1" | "Q3"]> | null;
}

export interface EditTimePeriodsV3 {
  operation: "replace" | "add" | "remove" | "keep" | "inherit" | "clear";
  text?: string;
  field: "time.periods";
  value: Array<"FY" | "HY" | "Q1" | "Q3">;
}

export interface EditTimeQuartersV3 {
  operation: "replace" | "add" | "remove" | "keep" | "inherit" | "clear";
  text?: string;
  field: "time.quarters";
  value: Array<1 | 2 | 3 | 4>;
}

export interface EditTimeSingleQuarterV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "time.single_quarter";
  value: boolean;
}

export interface EditTimeSpanV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "time.span";
  value: number | null;
}

export interface EditTimeYearsV3 {
  operation: "replace" | "add" | "remove" | "keep" | "inherit" | "clear";
  text?: string;
  field: "time.years";
  value: Array<number>;
}

export interface ExecutionV3 {
  turn_id: string;
  data_version: string;
  resolved_periods: Record<string, Array<[number, "FY" | "HY" | "Q1" | "Q3"]>>;
  time_rule: string;
  fact_refs: Array<FactReferenceV3>;
  status: "completed" | "partial" | "no_data" | "clarification" | "cancelled" | "failed";
  conditions?: ConditionsV3 | null;
  goal_conditions?: Record<string, ConditionsV3>;
}

export interface FactV3 {
  version?: 3;
  id: string;
  data_version: string;
  stock_code: string;
  company: string;
  year: number;
  period: "FY" | "HY" | "Q1" | "Q3";
  metric: string;
  scope: "consolidated" | "parent";
  value: string;
  unit: "元" | "%" | "元/股";
  status: "verified" | "derived" | "conflict" | "scope_unknown" | "unverified";
  source?: SourceV3 | null;
  formula?: string | null;
  inputs?: Array<string>;
}

export interface FactReferenceV3 {
  id: string;
  data_version: string;
}

export interface GoalV3 {
  id: string;
  kind: "lookup" | "compare" | "rank" | "chart" | "quote" | "cause" | "concept" | "rules" | "catalog" | "sign" | "unsupported";
  text: string;
  intent_source?: string;
  context_goal_id?: string | null;
  context_conditions?: ConditionsV3 | null;
  selection?: GoalSelectionV3 | null;
  condition_edits?: Array<CompanyEditV3 | MetricEditV3 | ScopeEditV3 | CollectionEditV3 | CalculationEditV3 | AxisEditV3 | EditTimeModeV3 | EditTimeYearsV3 | EditTimePeriodsV3 | EditTimeSpanV3 | EditTimePairsV3 | EditTimeSingleQuarterV3 | EditTimeQuartersV3 | EditPresentationUnitV3 | EditPresentationDecimalsV3 | EditPresentationFormatV3 | EditPresentationChartTypeV3 | EditPresentationOrderV3 | EditPresentationLimitV3 | EditPresentationIncludeInputsV3 | EditRestrictionsNoQueryV3 | EditRestrictionsNoChartV3 | EditRestrictionsNoRepeatV3 | EditRestrictionsExcludedCodesV3 | EditRestrictionsExcludedMetricsV3>;
  catalog_target?: "companies" | "periods" | "metrics" | "capabilities" | null;
  execution_ref?: string | null;
  quote_mode?: "literal" | "location" | null;
  concept_mode?: "definition" | "difference" | "implication" | null;
  clarification?: Array<string>;
}

export interface GoalResultV3 {
  id: string;
  kind: "lookup" | "compare" | "rank" | "chart" | "quote" | "cause" | "concept" | "rules" | "catalog" | "sign" | "unsupported";
  status: "completed" | "partial" | "no_data" | "unsupported" | "failed";
  fact_ids?: Array<string>;
  evidence_ids?: Array<string>;
  detail?: string;
}

export interface GoalSelectionV3 {
  codes?: Array<string> | null;
  metrics?: Array<string> | null;
  scope?: "consolidated" | "parent" | null;
  time?: TimePatchV3 | null;
  presentation?: PresentationPatchV3 | null;
  calculation?: "none" | "difference" | "yoy" | "relative_percent" | "percentage_points" | null;
  comparison_axis?: "years" | "companies" | "none" | null;
}

export interface HashedOriginalRegionV3 {
  page: number;
  bbox: [number, number, number, number];
  text_sha256: string;
}

export interface InterruptedRequestV3 {
  turn_id: string;
  question: string;
  status: "failed" | "cancelled";
  confirmed_fields?: Array<"codes" | "metrics">;
  uncertain_paths?: Array<string> | null;
}

export interface MemoryEditV3 {
  field: "company_context" | "financial_context";
  operation?: "clear";
  text: string;
}

export interface MetricEditV3 {
  operation: "replace" | "add" | "remove" | "keep" | "inherit" | "clear";
  text?: string;
  field: "metrics";
  value: Array<"operating_revenue" | "total_operating_revenue" | "main_business_revenue" | "net_profit" | "attributable_net_profit" | "deducted_attributable_net_profit" | "operating_cost" | "gross_profit" | "gross_margin" | "net_margin" | "eps_basic" | "eps_diluted" | "roe_weighted" | "roe_weighted_deducted" | "roe_diluted" | "total_assets" | "total_liabilities" | "total_equity" | "cash" | "receivables" | "inventory" | "trading_assets" | "construction" | "payables" | "advances" | "contract_liabilities" | "short_loans" | "retained_earnings" | "operating_profit" | "total_profit" | "other_income" | "selling_expense" | "administration_expense" | "finance_expense" | "research_expense" | "tax_surcharges" | "total_operating_cost" | "asset_impairment" | "credit_impairment" | "operating_cash_flow" | "investing_cash_flow" | "financing_cash_flow" | "net_cash_change" | "sales_cash" | "investment_cash_paid" | "cash_begin" | "cash_end" | "debt_ratio" | "net_assets_per_share" | "operating_cash_per_share" | "operating_revenue_reported_yoy" | "total_operating_revenue_reported_yoy" | "attributable_net_profit_reported_yoy" | "net_profit_reported_yoy" | "deducted_attributable_net_profit_reported_yoy" | "total_assets_reported_yoy" | "total_liabilities_reported_yoy" | "net_cash_change_reported_yoy" | "total_assets_reported_change_vs_year_end" | "total_liabilities_reported_change_vs_year_end">;
}

export interface OriginV3 {
  kind: "current" | "context" | "default";
  text: string;
  turn_id?: string;
}

export interface OriginalCellProofV3 {
  value: OriginalRegionV3;
  row: OriginalRegionV3;
  heading: OriginalRegionV3;
  context: OriginalRegionV3;
  scope_context?: OriginalRegionV3 | null;
}

export interface OriginalRegionV3 {
  page: number;
  bbox: [number, number, number, number];
  text: string;
}

export interface PresentationV3 {
  unit?: "元" | "万元" | "亿元" | "%" | "元/股" | null;
  decimals?: number | null;
  format?: "auto" | "text" | "table" | "chart";
  chart_type?: "line" | "bar" | "pie" | "scatter";
  order?: "asc" | "desc";
  limit?: number | null;
  include_inputs?: boolean;
}

export interface PresentationEditV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "presentation";
  value: PresentationPatchV3;
}

export interface PresentationPatchV3 {
  unit?: "元" | "万元" | "亿元" | "%" | "元/股" | null;
  decimals?: number | null;
  format?: "auto" | "text" | "table" | "chart" | null;
  chart_type?: "line" | "bar" | "pie" | "scatter" | null;
  order?: "asc" | "desc" | null;
  limit?: number | null;
  include_inputs?: boolean | null;
}

export interface RequestV3 {
  version?: 3;
  turn_id: string;
  question: string;
  continuity?: "continue" | "new" | "resume" | "clear";
  conditions: ConditionsV3;
  modifications?: Array<CompanyEditV3 | MetricEditV3 | ScopeEditV3 | CollectionEditV3 | CalculationEditV3 | AxisEditV3 | EditTimeModeV3 | EditTimeYearsV3 | EditTimePeriodsV3 | EditTimeSpanV3 | EditTimePairsV3 | EditTimeSingleQuarterV3 | EditTimeQuartersV3 | EditPresentationUnitV3 | EditPresentationDecimalsV3 | EditPresentationFormatV3 | EditPresentationChartTypeV3 | EditPresentationOrderV3 | EditPresentationLimitV3 | EditPresentationIncludeInputsV3 | EditRestrictionsNoQueryV3 | EditRestrictionsNoChartV3 | EditRestrictionsNoRepeatV3 | EditRestrictionsExcludedCodesV3 | EditRestrictionsExcludedMetricsV3 | TimeEditV3 | PresentationEditV3 | RestrictionEditV3>;
  memory_edits?: Array<MemoryEditV3>;
  clarification_choices?: Array<ClarificationChoicesV3>;
  goals: Array<GoalV3>;
  context_references?: Array<ContextReferenceV3>;
  company_mentions?: Array<CompanyMentionV3>;
  clarification?: Array<string>;
  unsupported?: Array<string>;
}

export interface RestrictionEditV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "restrictions";
  value: RestrictionPatchV3;
}

export interface RestrictionPatchV3 {
  no_query?: boolean | null;
  no_chart?: boolean | null;
  no_repeat?: boolean | null;
  excluded_codes?: Array<string> | null;
  excluded_metrics?: Array<"operating_revenue" | "total_operating_revenue" | "main_business_revenue" | "net_profit" | "attributable_net_profit" | "deducted_attributable_net_profit" | "operating_cost" | "gross_profit" | "gross_margin" | "net_margin" | "eps_basic" | "eps_diluted" | "roe_weighted" | "roe_weighted_deducted" | "roe_diluted" | "total_assets" | "total_liabilities" | "total_equity" | "cash" | "receivables" | "inventory" | "trading_assets" | "construction" | "payables" | "advances" | "contract_liabilities" | "short_loans" | "retained_earnings" | "operating_profit" | "total_profit" | "other_income" | "selling_expense" | "administration_expense" | "finance_expense" | "research_expense" | "tax_surcharges" | "total_operating_cost" | "asset_impairment" | "credit_impairment" | "operating_cash_flow" | "investing_cash_flow" | "financing_cash_flow" | "net_cash_change" | "sales_cash" | "investment_cash_paid" | "cash_begin" | "cash_end" | "debt_ratio" | "net_assets_per_share" | "operating_cash_per_share" | "operating_revenue_reported_yoy" | "total_operating_revenue_reported_yoy" | "attributable_net_profit_reported_yoy" | "net_profit_reported_yoy" | "deducted_attributable_net_profit_reported_yoy" | "total_assets_reported_yoy" | "total_liabilities_reported_yoy" | "net_cash_change_reported_yoy" | "total_assets_reported_change_vs_year_end" | "total_liabilities_reported_change_vs_year_end"> | null;
}

export interface RestrictionsV3 {
  no_query?: boolean;
  no_chart?: boolean;
  no_repeat?: boolean;
  excluded_codes?: Array<string>;
  excluded_metrics?: Array<string>;
}

export interface ScopeEditV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "scope";
  value: "consolidated" | "parent";
}

export interface SourceV3 {
  document_id: string;
  document_version: string;
  source_sha256: string;
  source_path: string;
  page: number;
  table: string;
  row: string;
  column: string;
  row_index: number;
  column_index: number;
  raw_value: string;
  raw_unit: string;
  raw_precision: number;
  literal: string;
  extraction: "ocr" | "pdf_text" | "manual";
  verification: "literal_checked" | "human_checked" | "unverified";
  original_cell?: OriginalCellProofV3 | null;
  scope_proof?: StatementScopeProofV3 | null;
}

export interface StatementScopeProofV3 {
  caption: OriginalRegionV3;
  family: "资产负债表" | "利润表" | "现金流量表" | "notes" | "indicators";
  value_region: HashedOriginalRegionV3;
  label_region: HashedOriginalRegionV3;
}

export interface TaskRecordV3 {
  version?: 3;
  task_id: string;
  client_request_id: string;
  session_uid: string;
  question?: string;
  status: "queued" | "running" | "cancelling" | "completed" | "cancelled" | "failed";
  deadline: number;
  saved?: boolean;
  result?: Record<string, unknown> | null;
  error?: string | null;
}

export interface TimeEditV3 {
  operation: "replace" | "inherit" | "clear";
  text?: string;
  field: "time";
  value: TimePatchV3;
}

export interface TimePatchV3 {
  mode?: "explicit" | "calendar_years" | "latest_common" | "latest_each" | "latest" | null;
  years?: Array<number> | null;
  periods?: Array<"FY" | "HY" | "Q1" | "Q3"> | null;
  single_quarter?: boolean | null;
  quarters?: Array<1 | 2 | 3 | 4> | null;
  span?: number | null;
  pairs?: Array<[number, "FY" | "HY" | "Q1" | "Q3"]> | null;
}

export interface TimeSelectionV3 {
  mode?: "explicit" | "calendar_years" | "latest_common" | "latest_each" | "latest";
  years?: Array<number>;
  periods?: Array<"FY" | "HY" | "Q1" | "Q3">;
  single_quarter?: boolean;
  quarters?: Array<1 | 2 | 3 | 4>;
  span?: number | null;
  pairs?: Array<[number, "FY" | "HY" | "Q1" | "Q3"]> | null;
}

export interface UnderstandingV3 {
  topic: "financial" | "concept" | "rules" | "catalog" | "greeting" | "other";
  continuity: "continue" | "new" | "resume" | "clear";
  context_references?: Array<ContextReferenceV3>;
  company_mentions?: Array<CompanyMentionV3>;
  goals: Array<GoalV3>;
  modifications: Array<CompanyEditV3 | MetricEditV3 | ScopeEditV3 | CollectionEditV3 | CalculationEditV3 | AxisEditV3 | EditTimeModeV3 | EditTimeYearsV3 | EditTimePeriodsV3 | EditTimeSpanV3 | EditTimePairsV3 | EditTimeSingleQuarterV3 | EditTimeQuartersV3 | EditPresentationUnitV3 | EditPresentationDecimalsV3 | EditPresentationFormatV3 | EditPresentationChartTypeV3 | EditPresentationOrderV3 | EditPresentationLimitV3 | EditPresentationIncludeInputsV3 | EditRestrictionsNoQueryV3 | EditRestrictionsNoChartV3 | EditRestrictionsNoRepeatV3 | EditRestrictionsExcludedCodesV3 | EditRestrictionsExcludedMetricsV3 | TimeEditV3 | PresentationEditV3 | RestrictionEditV3>;
  memory_edits?: Array<MemoryEditV3>;
  clarification: Array<string>;
  unsupported: Array<string>;
  unknown_companies: Array<string>;
  claimed_sign?: "positive" | "negative" | "zero" | "none";
}

export interface VerificationV3 {
  version?: 3;
  numeric: Array<CheckV3>;
  request: Array<CheckV3>;
  evidence: Array<CheckV3>;
  status: "pass" | "partial" | "fail";
}

