"""作品说明：由 Python v3 统一定义生成共享模式和 TypeScript 类型。"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.agent.v3.contracts import DialogueState, Fact, Modification, Request, Strict, TaskRecord, Verification, GoalResult, Understanding


class ContractBundle(Strict):
    understanding: Understanding
    request: Request
    modification: Modification
    dialogue_state: DialogueState
    fact: Fact
    task: TaskRecord
    verification: Verification
    goal_result: GoalResult


def ts_type(schema):
    if '$ref' in schema:
        return schema['$ref'].split('/')[-1] + 'V3'
    if 'const' in schema:
        return json.dumps(schema['const'], ensure_ascii=False)
    if 'enum' in schema:
        return ' | '.join(json.dumps(v, ensure_ascii=False) for v in schema['enum'])
    if 'anyOf' in schema:
        return ' | '.join(ts_type(s) for s in schema['anyOf'])
    if 'oneOf' in schema:
        return ' | '.join(ts_type(s) for s in schema['oneOf'])
    t=schema.get('type')
    if t=='array':
        if 'prefixItems' in schema:
            return '[' + ', '.join(ts_type(s) for s in schema['prefixItems']) + ']'
        return f'Array<{ts_type(schema.get("items") or {})}>'
    if t=='object':
        additional = schema.get('additionalProperties')
        return 'Record<string, ' + ts_type(additional if isinstance(additional, dict) else {}) + '>'
    return {'integer':'number','number':'number','boolean':'boolean','string':'string','null':'null'}.get(t,'unknown')


def generate():
    schema=ContractBundle.model_json_schema()
    schema['$id']='https://finsight.local/contracts/v3'
    schema['$schema']='https://json-schema.org/draft/2020-12/schema'
    lines=['// Generated by scripts/generate_v3_contracts.py. Edit the Python contract, then regenerate.']
    for name, definition in schema['$defs'].items():
        lines.append(f'export interface {name}V3 {{')
        required=set(definition.get('required',[]))
        for key, value in definition.get('properties',{}).items():
            lines.append(f'  {key}{"" if key in required else "?"}: {ts_type(value)};')
        lines.append('}\n')
    return json.dumps(schema,ensure_ascii=False,indent=2)+'\n', '\n'.join(lines)+'\n'


if __name__=='__main__':
    schema, ts=generate()
    (ROOT/'shared').mkdir(exist_ok=True)
    (ROOT/'shared/finsight-v3.schema.json').write_text(schema,encoding='utf-8')
    (ROOT/'frontend/src/types/finsight-v3.ts').write_text(ts,encoding='utf-8')
    print('v3 JSON Schema and TypeScript generated')
